version: "3.8"

services:

  tesseract:
    container_name: tesseract
    build: .
    ports:
      - 9090:9090
    volumes:
      - "./data/server:/data"
    environment:
      # Specify log level
      - LOG_LEVEL=DEBUG

      # Specify the Label Studio URL (ipconfig in cmd) and API key to access
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST}
      - LABEL_STUDIO_ACCESS_TOKEN=${LABEL_STUDIO_ACCESS_TOKEN}
